[project]
name = "chapter03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ahnugent", email = "allennugent@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.0",
    "jupyter>=1.0.0",
    "langchain-core>=0.3.0,<0.4.0",
    "pydantic>=2.9.0,<3.0.0",
    "python-dotenv>=1.1.0,<2.0.0",
]

[project.scripts]
chapter03 = "chapter03:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
